<a href="https://colab.research.google.com/github/Don-Youssef/ai-chatbot-colab/blob/main/Simple_Chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing

In [ ]:
import json
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import one_hot, Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense
import pickle as pkl
import numpy as np

#loading JSON data from a file into a Python dictionary

In [ ]:
with open('/content/data.json') as file:
  data = json.load(file) # you can also get dataset from kaggle
print(data)

{'data': [{'label': 'greeting', 'patterns': ['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay'], 'responses': ['Hello', 'Hi', 'Hi there', 'Hey']}, {'label': 'about', 'patterns': ['Who are you?', 'What are you?', 'Who you are?'], 'responses': ["I'm Zain, your bot assistant!", "I'm Zain, an Artificial Intelligent bot!", "I'm Zain, an Amit Artificial Intelligent bot"]}, {'label': 'name', 'patterns': ['What is your name?', 'What should I call you?', "What's your name?"], 'responses': ['You can call me Zain', "I'm Zain!", 'Just call me as Zain']}, {'label': 'help', 'patterns': ['Could you help me?', 'Give me a hand please', 'Can you help?', 'What can you do for me?', 'I need a support', 'I need a help', 'Support me please'], 'responses': ['Tell me how can assist you', 'Tell me your problem to assist you', 'Yes Sure, How can I support you?']}, {'label': 'sad', 'patterns': ["I'm so sad", "I'm sad", 'I feel sad', 'I feel so sad', 'I am sad', "I'm alone", 'I have a lot of problems'], 'responses':

#extracting patterns, labels, and responses from a nested dictionary structure into separate lists for training a chatbot or similar natural language processing model

In [ ]:
traning_examples = []
traning_labels = []
traning_responses = []
for example in data['data']:
  for pattern in example['patterns']:
    traning_examples.append(pattern)
    traning_labels.append(example['label'])
    traning_responses.append(example['responses'])
print(traning_examples)
print(traning_labels)
print(traning_responses)

['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay', 'Who are you?', 'What are you?', 'Who you are?', 'What is your name?', 'What should I call you?', "What's your name?", 'Could you help me?', 'Give me a hand please', 'Can you help?', 'What can you do for me?', 'I need a support', 'I need a help', 'Support me please', "I'm so sad", "I'm sad", 'I feel sad', 'I feel so sad', 'I am sad', "I'm alone", 'I have a lot of problems', 'I am depressed', 'I need encouragement', "I'm so frustrated", "I'm so frustrated with myself because I lost confidence", 'Thanks', 'Thank you', "That's helpful", 'Thanks for the help', 'Bye', 'See you later', 'Goodbye']
['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'about', 'about', 'about', 'name', 'name', 'name', 'help', 'help', 'help', 'help', 'help', 'help', 'help', 'sad', 'sad', 'sad', 'sad', 'sad', 'sad', 'sad', 'positive_sen', 'positive_sen', 'positive_sen', 'positive_sen', 'thanks', 'thanks', 'thanks', 'thanks', 'goodbye', 'goodbye', 'goodbye'

#cleaning text data by converting sentences to lowercase

In [ ]:
def clean_text(sentences):
  cleaned_sentences = []
  for sentence in sentences:
    sentence = sentence.lower()
    cleaned_sentences.append(sentence)
  return cleaned_sentences
cleaned_traning_examples = clean_text(traning_examples)
print(cleaned_traning_examples)

['hi', 'hey', 'is anyone there?', 'hello', 'hay', 'who are you?', 'what are you?', 'who you are?', 'what is your name?', 'what should i call you?', "what's your name?", 'could you help me?', 'give me a hand please', 'can you help?', 'what can you do for me?', 'i need a support', 'i need a help', 'support me please', "i'm so sad", "i'm sad", 'i feel sad', 'i feel so sad', 'i am sad', "i'm alone", 'i have a lot of problems', 'i am depressed', 'i need encouragement', "i'm so frustrated", "i'm so frustrated with myself because i lost confidence", 'thanks', 'thank you', "that's helpful", 'thanks for the help', 'bye', 'see you later', 'goodbye']


#encoding the training labels using Label Encoding

In [ ]:
encoder = LabelEncoder()
traning_labels = encoder.fit_transform(traning_labels)
print(traning_labels)
pkl.dump(encoder, open('encoder.pkl', 'wb'))

[2 2 2 2 2 0 0 0 4 4 4 3 3 3 3 3 3 3 6 6 6 6 6 6 6 5 5 5 5 7 7 7 7 1 1 1]


#converting the training labels into a one-hot encoded format using to_categorical

In [ ]:
traning_labels = to_categorical(traning_labels)
print(traning_labels)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]


#Tokenizing and Sequencing Text Data

In [ ]:
tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(cleaned_traning_examples)
sequences = tokenizer.texts_to_sequences(cleaned_traning_examples)
print(sequences)
pkl.dump(tokenizer, open('tokenizer.pkl', 'wb'))

[[24], [25], [12, 26, 27], [28], [29], [13, 10, 2], [5, 10, 2], [13, 2, 10], [5, 12, 14, 15], [5, 30, 1, 31, 2], [32, 14, 15], [33, 2, 6, 7], [34, 7, 8, 35, 16], [17, 2, 6], [5, 17, 2, 36, 18, 7], [1, 11, 8, 19], [1, 11, 8, 6], [19, 7, 16], [3, 9, 4], [3, 4], [1, 20, 4], [1, 20, 9, 4], [1, 21, 4], [3, 37], [1, 38, 8, 39, 40, 41], [1, 21, 42], [1, 11, 43], [3, 9, 22], [3, 9, 22, 44, 45, 46, 1, 47, 48], [23], [49, 2], [50, 51], [23, 18, 52, 6], [53], [54, 2, 55], [56]]


#Padding of Text Sequences

In [ ]:
paded_sequences = pad_sequences(sequences, truncating='pre',  maxlen=20)
print(paded_sequences)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12 26 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 29]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13 10  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5 10  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  2 10]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5 12 14 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5 30  1 31  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32 14 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 33  2  6  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 34  7  8 35 16]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 17  2  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  5 17  2 36 18  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 11

#Defining and summarizing a Keras Sequential model for text classification

In [ ]:
vocabulary_size = 100
embedding_dimension = 10
max_length = 20
model = Sequential()
model.add(Embedding(input_dim=vocabulary_size, output_dim=embedding_dimension))
model.add(GlobalAveragePooling1D())
model.add(Dense(units=10, activation='relu'))
model.add(Dense(units=9, activation='relu'))
model.add(Dense(units=8, activation='softmax'))
sample_input = np.random.randint(vocabulary_size, size=(1, max_length))
model(sample_input)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 20, 10)            │         1,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (1, 10)                │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (1, 10)                │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (1, 9)                 │            99 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (1, 8)                 │            80 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,289 (5.04 KB)

 Trainable params: 1,289 (5.04 KB)

 Non-trainable params: 0 (0.00 B)

#Compiling and training a Keras model for text classification

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(np.array(paded_sequences), traning_labels, epochs=2000)
model.save("model.h5")

Epoch 1/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 5s 2s/step - accuracy: 1.0000 - loss: 0.0042
Epoch 2/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 1.0000 - loss: 0.0040 
Epoch 3/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0046
Epoch 4/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0047
Epoch 5/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.0045
Epoch 6/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.0042
Epoch 7/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0039
Epoch 8/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0037 
Epoch 9/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.0037
Epoch 10/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.0037
Epoch 11/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0036
Epoch 12/2000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy:

#Preprocessing Text Input for Model Prediction

In [ ]:
input = 'hello'
sequences_input = tokenizer.texts_to_sequences([input])
paded_sequences_input = pad_sequences(sequences_input, truncating='pre',  maxlen=20)
print(paded_sequences_input)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]]


#Predicting Intent using the Trained Model

In [ ]:
print(model.predict(np.array(paded_sequences_input)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 372ms/step
[[9.1405087e-07 1.5703209e-06 9.9999487e-01 1.9228830e-09 9.1212411e-12
  1.8004008e-06 3.3609393e-10 8.0281671e-07]]


#Mapping Model Prediction to Class Label

In [ ]:
inverse_label_input = encoder.inverse_transform(model.predict(np.array(paded_sequences_input)).argmax(axis=1).reshape(1))
print(inverse_label_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['greeting']


#Chatbot Interface

In [ ]:
# ================= BACKEND =================
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from IPython.display import display, HTML
from google.colab import output

def process_input(user_message):
    try:
        sequences_input = tokenizer.texts_to_sequences([user_message])
        padded = pad_sequences(sequences_input, truncating='pre', maxlen=20)
        prediction = model.predict(np.array(padded), verbose=0)

        label_index = int(prediction.argmax(axis=1)[0])
        label_name = encoder.inverse_transform([label_index])[0]

        for item in data['data']:
            if str(item['label']).strip().lower() == str(label_name).strip().lower():
                return str(np.random.choice(item['responses']))

        return "I don't understand."
    except Exception as e:
        return "Error: " + str(e)

output.register_callback('chat.process', process_input)


# ================= FRONTEND =================
display(HTML("""

<style>
body {
    margin:0;
    background:#000;
    font-family: monospace;
    overflow:hidden;
    color:orange;
}

#boot {
    position:absolute;
    width:100%;
    height:100%;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
    color:#00ff00;
    font-weight:bold;
}
.boot-text { opacity:0; transition:0.5s; }

#matrix {
    position:fixed;
    top:0;
    left:0;
    width:100%;
    height:100%;
    z-index:0;
}

.container {
    width:80%;
    max-width:800px;
    margin:40px auto;
    display:none;
    position:relative;
    z-index:2;
}

#bot-eye {
    position:absolute;
    width:24px;
    height:24px;
    border-radius:50%;
    background:#ff0000;
    border:2px solid #800000;
    top:10px;
    right:10px;
    box-shadow:0 0 15px #ff0000,0 0 30px orange;
    overflow:hidden;
}
#bot-eye::after {
    content:'';
    position:absolute;
    width:8px;
    height:8px;
    background:black;
    border-radius:50%;
    top:50%;
    left:50%;
    transform:translate(-50%,-50%);
}
#bot-eye::before {
    content:'';
    position:absolute;
    width:6px;
    height:6px;
    background:#fff3;
    border-radius:50%;
    top:25%;
    left:30%;
}

.pulse {
    animation:pulse 1s infinite alternate;
}
@keyframes pulse {
    from {box-shadow:0 0 15px #ff0000,0 0 30px orange;}
    to {box-shadow:0 0 30px #ff0000,0 0 60px orange;}
}
.blink {
    animation:blink 0.2s;
}
@keyframes blink {
    from {box-shadow:0 0 30px #ff0000,0 0 60px orange;}
    to {box-shadow:0 0 10px #ff0000,0 0 20px orange;}
}

.chat-box {
    background:#111;
    height:450px;
    border-radius:10px;
    padding:20px;
    overflow-y:auto;
    box-shadow:0 0 30px rgba(255,122,0,0.2);
}

.msg {
    max-width:70%;
    padding:12px;
    margin:8px 0;
    border-radius:12px;
    animation:glitch 0.3s;
    font-weight:bold;
}
@keyframes glitch {
    0%{transform:translate(0);}
    25%{transform:translate(-2px,2px);}
    50%{transform:translate(2px,-2px);}
    75%{transform:translate(-2px,-2px);}
    100%{transform:translate(0);}
}

.user {
    background:#1f1f1f;
    color:orange;
    margin-left:auto;
}
.bot {
    background:#1a1a1a;
    color:#ff3300;
    text-shadow:0 0 6px #ff3300,0 0 12px #ff0000;
}

.typing {
    color:#00cc00;
    font-style:italic;
}

.input-area {
    display:flex;
    margin-top:15px;
}

input {
    flex:1;
    padding:12px;
    background:#1a1a1a;
    border:none;
    color:orange;
    border-radius:8px;
    outline:none;
}

button {
    padding:12px 18px;
    margin-left:8px;
    border:2px solid #ff7a00;
    background:transparent;
    color:#ff7a00;
    border-radius:8px;
    cursor:pointer;
}
button:hover {
    background:#ff7a00;
    color:#000;
}
</style>

<div id="boot">
    <div class="boot-text">Initializing system...</div>
    <div class="boot-text">Loading AI core...</div>
    <div class="boot-text">Access granted</div>
</div>

<canvas id="matrix"></canvas>

<div class="container">
    <div id="bot-eye" class="pulse"></div>
    <div class="chat-box" id="chat"></div>
    <div class="input-area">
        <input id="inp" placeholder="Type..." onkeydown="if(event.key==='Enter') send()">
        <button onclick="send()">➤</button>
    </div>
</div>

<script>
let lines=document.querySelectorAll(".boot-text");
lines.forEach((l,i)=>setTimeout(()=>l.style.opacity=1,i*1000));
setTimeout(()=>{
    document.getElementById("boot").style.display="none";
    document.querySelector(".container").style.display="block";
},3500);

let canvas = document.getElementById("matrix");
let ctx = canvas.getContext("2d");

let letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*+=<>!?";
let fontSize = 18;
let columns;
let drops;

function resizeCanvas(){
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    initMatrix();
}
window.addEventListener("resize", resizeCanvas);

function initMatrix(){
    columns = Math.floor(canvas.width / fontSize);
    drops = [];
    for(let i=0;i<columns;i++){
        drops[i] = Math.random() * canvas.height;
    }
}

function drawMatrix(){
    ctx.fillStyle = "rgba(0,0,0,1)";
    ctx.fillRect(0,0,canvas.width,canvas.height);

    ctx.font = fontSize + "px monospace";
    ctx.fillStyle = "#ff7a00";
    ctx.shadowColor = "#ff7a00";
    ctx.shadowBlur = 14;

    for(let i=0;i<drops.length;i++){
        let text = letters[Math.floor(Math.random()*letters.length)];
        ctx.fillText(text, i*fontSize, drops[i]);
        drops[i] += fontSize;

        if(drops[i] > canvas.height + fontSize){
            drops[i] = 0;
        }
    }
}

resizeCanvas();
setInterval(drawMatrix, 50);

document.addEventListener("mousemove",e=>{
    let eye=document.getElementById("bot-eye");
    let rect=eye.getBoundingClientRect();
    let dx=(e.clientX-(rect.left+12))/10;
    let dy=(e.clientY-(rect.top+12))/10;
    eye.style.transform=`translate(${dx}px,${dy}px)`;
});

function add(text,cls){
    let chat=document.getElementById("chat");
    let div=document.createElement("div");
    div.className="msg "+cls;
    div.innerText=text;
    chat.appendChild(div);
    chat.scrollTop=chat.scrollHeight;

    if(cls==="bot"){
        let eye=document.getElementById("bot-eye");
        eye.classList.add("blink");
        setTimeout(()=>eye.classList.remove("blink"),200);
    }
}

async function send(){
    let input=document.getElementById("inp");
    let text=input.value;
    if(!text) return;

    add(text,"user");
    input.value="";

    let typing=document.createElement("div");
    typing.className="msg typing";
    typing.innerText="typing...";
    document.getElementById("chat").appendChild(typing);

    try{
        let res=await google.colab.kernel.invokeFunction('chat.process',[text],{});
        let reply=res.data['application/json'] || res.data['text/plain'] || "No response";
        typing.remove();
        add(reply,"bot");
    }catch(e){
        typing.remove();
        add("Error","bot");
    }
}
</script>
"""))